vich_uploader:
    db_driver: orm

    mappings:
        category_images:
            uri_prefix: /uploads/categories
            upload_destination: '%kernel.project_dir%/public/uploads/categories'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        manual_payment_proofs:
            uri_prefix: /uploads/manual_payments
            upload_destination: '%kernel.project_dir%/public/uploads/manual_payments'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
